### ISSUE TITLE
errors when running "./Build.hs exe"

### ISSUE THREAD

**Issue by vincent-hui** [mstksg/backprop#10] opened 2018-08-08 09:51 UTC
I am trying to build examples by running "./Build.hs exe". However, build fails.
How to solve it? I am using Ubuntu 16.04

Thank a lot.

```
# stack (for install)
backprop-0.2.6.1: configure (lib)
Configuring backprop-0.2.6.1...
backprop-0.2.6.1: build (lib)
Preprocessing library for backprop-0.2.6.1..
Building library for backprop-0.2.6.1..
ignoring (possibly broken) abi-depends field for packages
backprop-0.2.6.1: copy/register
Installing library in /home/vincent/worksapce/backprop/.stack-work/install/x86_64-linux/nightly-2018-08-06/8.4.3/lib/x86_64-linux-ghc-8.4.3/backprop-0.2.6.1-1KhuolUzAbT8z2lKXwLAVK
Registering library for backprop-0.2.6.1..
# stack (for samples-exe/extensible-neural)
[1 of 1] Compiling Main             ( samples/extensible-neural.lhs, samples/extensible-neural.o )

samples/extensible-neural.lhs:51:3: error:
    Could not find module ‘Data.List.Split’
    Use -v to see a list of the files searched for.
   |
51 | > import           Data.List.Split
   |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

samples/extensible-neural.lhs:60:3: error:
    Could not find module ‘Lens.Micro.TH’
    Perhaps you meant
      Lens.Micro (from microlens-0.4.9.1)
      Lens.Micro.Type (from microlens-0.4.9.1)
    Use -v to see a list of the files searched for.
   |
60 | > import           Lens.Micro.TH
   |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

samples/extensible-neural.lhs:63:3: error:
    Could not find module ‘Numeric.LinearAlgebra.Static’
    Use -v to see a list of the files searched for.
   |
63 | > import           Numeric.LinearAlgebra.Static
   |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

samples/extensible-neural.lhs:69:3: error:
    Could not find module ‘Numeric.LinearAlgebra’
    Use -v to see a list of the files searched for.
   |
69 | > import qualified Numeric.LinearAlgebra           as HM
   |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

samples/extensible-neural.lhs:70:3: error:
    Could not find module ‘System.Random.MWC’
    Perhaps you meant System.Random (from random-1.1)
    Use -v to see a list of the files searched for.
   |
70 | > import qualified System.Random.MWC               as MWC
   |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

samples/extensible-neural.lhs:71:3: error:
    Could not find module ‘System.Random.MWC.Distributions’
    Use -v to see a list of the files searched for.
   |
71 | > import qualified System.Random.MWC.Distributions as MWC
   |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error when running Shake build system:
* exe
* samples-exe/extensible-neural
user error (Development.Shake.cmd, system command failed
Command: stack ghc --stack-yaml stack.yaml --package mnist-idx --package singletons --package one-liner-instances -- samples/extensible-neural.lhs -o samples-exe/extensible-neural -hidir .build -Wall -O2
Exit code: 1
Stderr:
samples/extensible-neural.lhs:51:3: error:
    Could not find module ‘Data.List.Split’
    Use -v to see a list of the files searched for.
   |
51 | > import           Data.List.Split
   |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

samples/extensible-neural.lhs:60:3: error:
    Could not find module ‘Lens.Micro.TH’
    Perhaps you meant
      Lens.Micro (from microlens-0.4.9.1)
      Lens.Micro.Type (from microlens-0.4.9.1)
    Use -v to see a list of the files searched for.
   |
60 | > import           Lens.Micro.TH
   |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

samples/extensible-neural.lhs:63:3: error:
    Could not find module ‘Numeric.LinearAlgebra.Static’
    Use -v to see a list of the files searched for.
   |
63 | > import           Numeric.LinearAlgebra.Static
   |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

samples/extensible-neural.lhs:69:3: error:
    Could not find module ‘Numeric.LinearAlgebra’
    Use -v to see a list of the files searched for.
   |
69 | > import qualified Numeric.LinearAlgebra           as HM
   |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

samples/extensible-neural.lhs:70:3: error:
    Could not find module ‘System.Random.MWC’
    Perhaps you meant System.Random (from random-1.1)
    Use -v to see a list of the files searched for.
   |
70 | > import qualified System.Random.MWC               as MWC
   |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

samples/extensible-neural.lhs:71:3: error:
    Could not find module ‘System.Random.MWC.Distributions’
    Use -v to see a list of the files searched for.
   |
71 | > import qualified System.Random.MWC.Distributions as MWC
   |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
)
```

**Comment by mstksg** [comment] 2018-08-08 22:20
Ah, thanks for the heads up!  Seems to be a regression when updating the stackage snapshot in b65d1aa4.  I'll try to upload a patch later today :)

**Comment by mstksg** [comment] 2018-08-08 23:06
Should be resolved in 06fed8bb9 !  Give it about a half hour for the fpcomplete mirrors to update though, since this reminded me to fix *hmatrix-backprop* as well :)

**Comment by vincent-hui** [comment] 2018-08-09 08:46
I failed to build again after update, but the error message became shorter.
Here is the error message

```
vincent@vincent-VirtualBox:~/worksapce/backprop$ ./Build.hs exe
# stack (for install)
# stack (for samples-exe/extensible-neural)
[1 of 1] Compiling Main             ( samples/extensible-neural.lhs, samples/extensible-neural.o )

samples/extensible-neural.lhs:60:3: error:
    Could not find module ‘Lens.Micro.TH’
    Perhaps you meant
      Lens.Micro (from microlens-0.4.9.1)
      Lens.Micro.Type (from microlens-0.4.9.1)
    Use -v to see a list of the files searched for.
   |
60 | > import           Lens.Micro.TH
   |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error when running Shake build system:
* exe
* samples-exe/extensible-neural
user error (Development.Shake.cmd, system command failed
Command: stack ghc --stack-yaml stack.yaml --package mnist-idx --package singletons --package one-liner-instances --package one-liner --package split --package hmatrix-backprop --package random --package mwc-random --package hmatrix-vector-sized --package vector-sized --package finite-typelits -- samples/extensible-neural.lhs -o samples-exe/extensible-neural -hidir .build -Wall -O2
Exit code: 1
Stderr:
samples/extensible-neural.lhs:60:3: error:
    Could not find module ‘Lens.Micro.TH’
    Perhaps you meant
      Lens.Micro (from microlens-0.4.9.1)
      Lens.Micro.Type (from microlens-0.4.9.1)
    Use -v to see a list of the files searched for.
   |
60 | > import           Lens.Micro.TH
   |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
)
```

**Comment by mstksg** [comment] 2018-08-09 20:49
Ah, sorry, must have missed that one :)  Stack scripts can be a bit weird.  Can you try again with the latest commit, bfed0ee?

**Closed as completed** 2018-08-13 23:43 UTC
